configured_endpoints: 38
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/morpheus%2Fmorpheus-marketplace-682fab38f13e604e90ae405c3eef691dedb86ac47614f137c93b374af20aeee4.yml
